# Use an official Elasticsearch image as a parent image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.0

# Set the heap size (optional, adjust as needed)
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

# Expose ports for communication
EXPOSE 9200 9300
