# Use an official Kibana image as a parent image
FROM docker.elastic.co/kibana/kibana:7.15.0

# Expose port for communication
EXPOSE 5601

# Set the Elasticsearch URL (modify as needed)
ENV ELASTICSEARCH_URL=http://elasticsearch:9200